[package]
name = "include-str-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
cargo_toml = { version = "0.20.4" }

[build-dependencies]
cargo_toml = { version = "0.20.4" }

[profile.release]
opt-level = 3
